services:
  mysql:
    image: mysql:8.0
    container_name: chefconnection-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chefconnection_db
      MYSQL_USER: ccuser
      MYSQL_PASSWORD: cc123!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: